version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install  # or pip install -r requirements.txt for Python
  build:
    commands:
      - echo Build started on `date`
      - echo Running app logic
      - python convert.py

artifacts:
  files:
    - '**/*'
